

export const dateFields = [
  "ContactPersonNumber",
  "ContactPersonName",
  "dueBill",
  "engineerName",
  "finalMomnumber",
  "actualStartDate",
  "actualEndDate",
  "visitDate",
  "visitendDate",
  "momDate",
  "momsrNo",
  "daysspendsite",
  "startDate",
  "endDate",
  "deleveryDate",
  "requestDate",
  "actualVisitDuration",
];

export const UserSideConst = [
  {
    htmlFor: "projectName",
    title: "Project Name",
    type: "text",
    id: "projectName",
    name: "projectName",
    placeholder: "Enter the project name",
    required: true,
    readOnly: true,
  },
  {
    htmlFor: "duration",
    title: "Project Duration",
    type: "text",
    id: "duration",
    name: "duration",
    placeholder: "Enter the project duration",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "expenseScope",
    title: "Expenses Scope",
    type: "text",
    id: "expenseScope",
    name: "expenseScope",
    placeholder: "Enter the Expense Scope",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "workScope",
    title: "Work Scope",
    type: "text",
    id: "workScope",
    name: "workScope",
    placeholder: "Enter the work scope",
    required: true,
    maxLength: 500,
    rows: 3,
  },
  {
    htmlFor: "jobNumber",
    title: "Project Job Number",
    type: "text",
    id: "jobNumber",
    name: "jobNumber",
    placeholder: "Enter the project job number",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "orderNumber",
    title: "Order Number",
    type: "text",
    id: "orderNumber",
    name: "orderNumber",
    placeholder: "Enter the Order number",
    required: false,
    readOnly: true,
  },
  {
    htmlFor: "momsrNo",
    title: "MOM Sr. No.",
    type: "text",
    id: "momsrNo",
    name: "momsrNo",
    placeholder: "Enter the MOM number",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "startDate",
    title: "Project Start Date",
    type: "date",
    id: "startDate",
    name: "startDate",
    placeholder: "Select the project start date",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "endDate",
    title: "Project End Date",
    type: "date",
    id: "endDate",
    name: "endDate",
    placeholder: "Select the project end date",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "visitDate",
    title: "Site Visit Start Date",
    type: "date",
    id: "visitDate",
    name: "visitDate",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "visitendDate",
    title: "Site Visit End Date",
    type: "date",
    id: "visitendDate",
    name: "visitendDate",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "momDate",
    title: "Mom Date",
    type: "date",
    id: "momDate",
    name: "momDate",
    required: false,
    readOnly: false,
  },
  {
    htmlFor: "location",
    title: "Location",
    type: "text",
    id: "location",
    name: "location",
    placeholder: "Enter the project location",
    required: true,
    readOnly: true,
  },
  {
    htmlFor: "engineerName",
    title: "Assigned Engineer Name",
    type: "text",
    id: "engineerName",
    name: "engineerName",
    placeholder: "Enter the Engineer Name",
    required: true,
    readOnly: true,
  },
  {
    htmlFor: "finalMomnumber",
    title: "Final Mom",
    type: "text",
    id: "finalMomnumber",
    name: "finalMomnumber",
    placeholder: "Enter the final mom number",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "billStatus",
    title: "Billing Status",
    id: "billStatus",
    name: "billStatus",
    required: true,
    options: [
      { value: "TBB", label: "TBB" },
      { value: "ALL BILLED", label: "ALL BILLED" },
      { value: "PART BILLED", label: "PART BILLED" },
      { value: "N/A", label: "N/A" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "supplyStatus",
    title: "Supply Status",
    id: "supplyStatus",
    name: "supplyStatus",
    required: true,
    options: [
      { value: "DISPACHED", label: "DISPACHED" },
      { value: "PENDING", label: "PENDING" },
      { value: "N/A", label: "N/A" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "soType",
    title: "SO Type",
    type: "select",
    id: "soType",
    name: "soType",
    required: false,
    options: [
      { value: "PROJECT", label: "PROJECT" },
      { value: "SERVICE", label: "SERVICE" },
      { value: "AMC", label: "AMC" },
      { value: "SUPPLY", label: "SUPPLY" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "entityType",
    title: "Entity",
    type: "select",
    id: "entityType",
    name: "entityType",
    required: false,
    options: [
      { value: "SI DELHI", label: "SI-DELHI" },
      { value: "SI PUNE", label: "SI-PUNE" },
      { value: "SI NOIDA", label: "SI-NOIDA" },
      { value: "MS DELHI", label: "MS-DELHI" },
    ],
    readOnly: true,
  },
  {
    htmlFor: "StartChecklist",
    title: "Start Check List Status",
    type: "select",
    id: "StartChecklist",
    name: "StartChecklist",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "currentEngineerName",
    title: "Enter your name",
    type: "text",
    id: "currentEngineerName",
    name: "currentEngineerName",
    placeholder: "Enter your name",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "EndChecklist",
    title: "End Check List Status",
    type: "select",
    id: "EndChecklist",
    name: "EndChecklist",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "BackupSubmission",
    title: "Backup Submission Status",
    type: "select",
    id: "BackupSubmission",
    name: "BackupSubmission",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "ExpensSubmission",
    title: "Expense Submission Status",
    type: "select",
    id: "ExpensSubmission",
    name: "ExpensSubmission",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "daysspendsite",
    title: "Days spend on site",
    type: "text",
    id: "daysspendsite",
    name: "daysspendsite",
    placeholder: "Enter the value",
    required: true,
  },
];
