export const formval = {
  projectName: "",
  engineerName: "",
  entityType: "SI DELHI",
  finalMomnumber: "",
  actualStartDate: "",
  actualEndDate: "",
  soType: "PROJECT",
  client: "",
  jobNumber: "",
  bill: "",
  dueBill: "",
  billStatus: "N/A",
  visitDate: "",
  visitendDate: "",
  momDate: "",
  momsrNo: "",
  endUser: "",
  orderNumber: "",
  orderDate: "",
  daysspendsite: "",
  startDate: "",
  endDate: "",
  description: "",
  location: "",
  status: "upcoming",
  priority: "high",
  duration: "",
  service: "Service not included",
  workScope: "",
  expenseScope: "",
  supplyStatus: "DISPATCHED",
  deleveryDate: "",
  requestDate: "",
  StartChecklist: "N/A",
  EndChecklist: "N/A",
  actualVisitDuration: "",
  ContactPersonNumber: "",
  ContactPersonName: "",
  ExpensSubmission: "N/A",
  BackupSubmission: "N/A",
};

export const dateFields = [
  // "projectName",
  // "client",
  // "jobNumber",
  // "orderNumber",
  // "orderDate",
  // "description",
  // "location",
  // "duration",
  // "workScope",
  // "expenseScope",
  // "bill",
  // "endUser",
  "ContactPersonNumber",
  "ContactPersonName",
  "dueBill",
  "engineerName",
  "finalMomnumber",
  "actualStartDate",
  "actualEndDate",
  "visitDate",
  "visitendDate",
  "momDate",
  "momsrNo",
  "daysspendsite",
  "startDate",
  "endDate",
  "deleveryDate",
  "requestDate",
  "actualVisitDuration",
];

export const InputConst = [
  {
    htmlFor: "projectName",
    title: "project Name",
    type: "text",
    id: "projectName",
    name: "projectName",
    placeholder: "Enter the project name",
    required: true,
  },
  {
    htmlFor: "duration",
    title: "Service days involved",
    type: "text",
    id: "duration",
    name: "duration",
    placeholder: "Enter the service days involved",
    required: true,
  },
  {
    htmlFor: "actualVisitDuration",
    title: "Actual Site Visit Duration",
    type: "text",
    id: "actualVisitDuration",
    name: "actualVisitDuration",
    placeholder: "Enter the actual site visit duration",
    required: true,
  },
  {
    htmlFor: "expenseScope",
    title: "Expenses Scope",
    type: "text",
    id: "expenseScope",
    name: "expenseScope",
    placeholder: "Enter the Expense Scope",
    required: true,
  },
  {
    htmlFor: "workScope",
    title: "Work Scope",
    type: "text",
    id: "workScope",
    name: "workScope",
    placeholder: "Enter the work scope",
    required: true,
    maxLength: 500,
    rows: 3,
  },
  {
    htmlFor: "client",
    title: "Client",
    type: "text",
    id: "client",
    name: "client",
    placeholder: "Enter the client details",
    required: true,
  },
  {
    htmlFor: "endUser",
    title: "End User",
    type: "text",
    id: "endUser",
    name: "endUser",
    placeholder: "Enter the EndUser details",
    required: true,
  },
  {
    htmlFor: "jobNumber",
    title: "Job Number",
    type: "text",
    id: "jobNumber",
    name: "jobNumber",
    placeholder: "Enter the job number",
    required: true,
  },
  {
    htmlFor: "orderNumber",
    title: "Order Number",
    type: "text",
    id: "orderNumber",
    name: "orderNumber",
    placeholder: "Enter the Order number",
    required: false,
  },
  {
    htmlFor: "bill",
    title: "Order value",
    type: "number",
    id: "bill",
    name: "bill",
    placeholder: "Enter the order value",
    required: true,
  },
  {
    htmlFor: "dueBill",
    title: "Bill pending",
    type: "number",
    id: "dueBill",
    name: "dueBill",
    placeholder: "Enter the pending bill",
    required: true,
  },
  {
    htmlFor: "momsrNo",
    title: "MOM Sr. No.",
    type: "text",
    id: "momsrNo",
    name: "momsrNo",
    placeholder: "Enter the MOM number",
    required: true,
  },
  {
    htmlFor: "startDate",
    title: "Project Start Date",
    type: "date",
    id: "startDate",
    name: "startDate",
    placeholder: "Select the project start date",
    required: true,
  },
  {
    htmlFor: "endDate",
    title: "Project End Date",
    type: "date",
    id: "endDate",
    name: "endDate",
    placeholder: "Select the project end date",
    required: true,
  },
  {
    htmlFor: "actualStartDate",
    title: "Project Actual Start Date",
    type: "date",
    id: "actualStartDate",
    name: "actualStartDate",
    placeholder: "Select the project actual start date",
    required: true,
  },
  {
    htmlFor: "actualEndDate",
    title: "Project Actual End Date",
    type: "date",
    id: "actualEndDate",
    name: "actualEndDate",
    placeholder: "Select the project actual end date",
    required: true,
  },
  {
    htmlFor: "requestDate",
    title: "Requested Date",
    type: "date",
    id: "requestDate",
    name: "requestDate",
    placeholder: "Select the requested date",
    required: true,
  },
  {
    htmlFor: "deleveryDate",
    title: "Delivery Date",
    type: "date",
    id: "deleveryDate",
    name: "deleveryDate",
    required: true,
  },
  {
    htmlFor: "visitDate",
    title: "Site Visit Start Date",
    type: "date",
    id: "visitDate",
    name: "visitDate",
    required: true,
  },
  {
    htmlFor: "visitendDate",
    title: "Site Visit End Date",
    type: "date",
    id: "visitendDate",
    name: "visitendDate",
    required: true,
  },
  {
    htmlFor: "momDate",
    title: "Mom Date",
    type: "date",
    id: "momDate",
    name: "momDate",
    required: false,
  },
  {
    htmlFor: "orderDate",
    title: "Order Date",
    type: "date",
    id: "orderDate",
    name: "orderDate",
    required: true,
  },
  {
    htmlFor: "location",
    title: "Location",
    type: "text",
    id: "location",
    name: "location",
    placeholder: "Enter the project location",
    required: true,
  },
  {
    htmlFor: "engineerName",
    title: "Engineer Name",
    type: "text",
    id: "engineerName",
    name: "engineerName",
    placeholder: "Enter the Engineer Name",
    required: true,
  },
  {
    htmlFor: "finalMomnumber",
    title: "Final Mom",
    type: "text",
    id: "finalMomnumber",
    name: "finalMomnumber",
    placeholder: "Enter the final mom number",
    required: true,
  },
  {
    htmlFor: "billStatus",
    title: "Billing Status",
    id: "billStatus",
    name: "billStatus",
    required: true,
    options: [
      { value: "TBB", label: "TBB" },
      { value: "ALL BILLED", label: "ALL BILLED" },
      { value: "PART BILLED", label: "PART BILLED" },
      { value: "N/A", label: "N/A" },
    ],
  },
  {
    htmlFor: "supplyStatus",
    title: "Supply Status",
    id: "supplyStatus",
    name: "supplyStatus",
    required: true,
    options: [
      { value: "DISPATCHED", label: "DISPATCHED" },
      { value: "PENDING", label: "PENDING" },
    ],
  },
  {
    htmlFor: "soType",
    title: "SO Type",
    type: "select",
    id: "soType",
    name: "soType",
    required: false,
    options: [
      { value: "PROJECT", label: "PROJECT" },
      { value: "SERVICE", label: "SERVICE" },
      { value: "AMC", label: "AMC" },
    ],
  },
  {
    htmlFor: "entityType",
    title: "Entity",
    type: "select",
    id: "entityType",
    name: "entityType",
    required: false,
    options: [
      { value: "SI DELHI", label: "SI-DELHI" },
      { value: "SI PUNE", label: "SI-PUNE" },
      { value: "SI NOIDA", label: "SI-NOIDA" },
      { value: "MS DELHI", label: "MS-DELHI" },
    ],
  },
  {
    htmlFor: "status",
    title: "Status",
    type: "select",
    id: "status",
    name: "status",
    required: true,
    options: [
      { value: "upcoming", label: "Up Coming" },
      { value: "pending", label: "pending" },
      { value: "completed", label: "completed" },
      { value: "running", label: "running" },
    ],
  },
  {
    htmlFor: "StartChecklist",
    title: "Start Check List Status",
    type: "select",
    id: "StartChecklist",
    name: "StartChecklist",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
  },
  {
    htmlFor: "priority",
    title: "Priority",
    type: "select",
    id: "priority",
    name: "priority",
    required: true,
    options: [
      { value: "high", label: "High" },
      { value: "medium", label: "Medium" },
      { value: "low", label: "Low" },
    ],
  },
  {
    htmlFor: "service",
    title: "Service",
    type: "select",
    id: "service",
    name: "service",
    required: true,
    options: [
      { value: "Service Included", label: "Include" },
      { value: "Service not included", label: "Not Included" },
    ],
  },
  {
    title: "Description",
    id: "description",
    name: "description",
    htmlFor: "description",
    maxLength: 400,
    rows: 4,
    placeholder: "Enter the project Description",
    required: true,
  },
  {
    htmlFor: "EndChecklist",
    title: "End Check List Status",
    type: "select",
    id: "EndChecklist",
    name: "EndChecklist",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "ContactPersonName",
    title: "Contact Person Name",
    type: "text",
    id: "ContactPersonName",
    name: "ContactPersonName",
    placeholder: "Enter the contact person name",
    required: true,
  },
  {
    htmlFor: "ContactPersonNumber",
    title: "Contact Person Number",
    type: "text",
    id: "ContactPersonNumber",
    name: "ContactPersonNumber",
    placeholder: "Enter the contact person number",
    required: true,
  },
  {
    htmlFor: "BackupSubmission",
    title: "Backup Submission Status",
    type: "select",
    id: "BackupSubmission",
    name: "BackupSubmission",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "ExpensSubmission",
    title: "Expense Submission Status",
    type: "select",
    id: "ExpensSubmission",
    name: "ExpensSubmission",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
];

export const UpdateConst = [
  {
    htmlFor: "projectName",
    title: "project Name",
    type: "text",
    id: "projectName",
    name: "projectName",
    placeholder: "Enter the project name",
    required: false,
  },
  {
    htmlFor: "duration",
    title: "Project Duration",
    type: "text",
    id: "duration",
    name: "duration",
    placeholder: "Enter the project duration",
    required: false,
  },
  {
    htmlFor: "actualVisitDuration",
    title: "Actual Site Visit Duration",
    type: "text",
    id: "actualVisitDuration",
    name: "actualVisitDuration",
    placeholder: "Enter the actual site visit duration",
    required: false,
  },
  {
    htmlFor: "expenseScope",
    title: "Expenses Scope",
    type: "text",
    id: "expenseScope",
    name: "expenseScope",
    placeholder: "Enter the Expense Scope",
    required: false,
  },
  {
    htmlFor: "workScope",
    title: "Work Scope",
    type: "text",
    id: "workScope",
    name: "workScope",
    placeholder: "Enter the work scope",
    required: true,
    maxLength: 500,
    rows: 3,
  },
  {
    htmlFor: "client",
    title: "Client",
    type: "text",
    id: "client",
    name: "client",
    placeholder: "Enter the client details",
    required: false,
  },
  {
    htmlFor: "endUser",
    title: "End User",
    type: "text",
    id: "endUser",
    name: "endUser",
    placeholder: "Enter the EndUser details",
    required: false,
  },
  {
    htmlFor: "jobNumber",
    title: "Project Job Number",
    type: "text",
    id: "jobNumber",
    name: "jobNumber",
    placeholder: "Enter the project job number",
    required: false,
  },
  {
    htmlFor: "orderNumber",
    title: "Order Number",
    type: "text",
    id: "orderNumber",
    name: "orderNumber",
    placeholder: "Enter the Order number",
    required: false,
  },
  {
    htmlFor: "bill",
    title: "Total Bill",
    type: "number",
    id: "bill",
    name: "bill",
    placeholder: "Enter the project Bill",
    required: false,
  },
  {
    htmlFor: "dueBill",
    title: "Due Bill",
    type: "number",
    id: "dueBill",
    name: "dueBill",
    placeholder: "Enter the project due Bill",
    required: false,
  },
  {
    htmlFor: "momsrNo",
    title: "MOM Sr. No.",
    type: "text",
    id: "momsrNo",
    name: "momsrNo",
    placeholder: "Enter the MOM number",
    required: false,
  },
  {
    htmlFor: "startDate",
    title: "Project Start Date",
    type: "date",
    id: "startDate",
    name: "startDate",
    placeholder: "Select the project start date",
    required: false,
  },
  {
    htmlFor: "endDate",
    title: "Project End Date",
    type: "date",
    id: "endDate",
    name: "endDate",
    placeholder: "Select the project end date",
    required: false,
  },
  {
    htmlFor: "actualStartDate",
    title: "Project Actual Start Date",
    type: "date",
    id: "actualStartDate",
    name: "actualStartDate",
    placeholder: "Select the project actual start date",
    required: false,
  },
  {
    htmlFor: "actualEndDate",
    title: "Project Actual End Date",
    type: "date",
    id: "actualEndDate",
    name: "actualEndDate",
    placeholder: "Select the project actual end date",
    required: false,
  },
  {
    htmlFor: "requestDate",
    title: "Requested Date",
    type: "date",
    id: "requestDate",
    name: "requestDate",
    placeholder: "Select the requested date",
    required: false,
  },
  {
    htmlFor: "deleveryDate",
    title: "Delivery Date",
    type: "date",
    id: "deleveryDate",
    name: "deleveryDate",
    required: false,
  },
  {
    htmlFor: "visitDate",
    title: "Site Visit Start Date",
    type: "date",
    id: "visitDate",
    name: "visitDate",
    required: false,
  },
  {
    htmlFor: "visitendDate",
    title: "Site Visit End Date",
    type: "date",
    id: "visitendDate",
    name: "visitendDate",
    required: false,
  },
  {
    htmlFor: "momDate",
    title: "Mom Date",
    type: "date",
    id: "momDate",
    name: "momDate",
    required: false,
  },
  {
    htmlFor: "orderDate",
    title: "Order Date",
    type: "date",
    id: "orderDate",
    name: "orderDate",
    required: false,
  },
  {
    htmlFor: "location",
    title: "Location",
    type: "text",
    id: "location",
    name: "location",
    placeholder: "Enter the project location",
    required: false,
  },
  {
    htmlFor: "engineerName",
    title: "Engineer Name",
    type: "text",
    id: "engineerName",
    name: "engineerName",
    placeholder: "Enter the Engineer Name",
    required: false,
  },
  {
    htmlFor: "finalMomnumber",
    title: "Final Mom",
    type: "text",
    id: "finalMomnumber",
    name: "finalMomnumber",
    placeholder: "Enter the final mom number",
    required: false,
  },
  {
    htmlFor: "billStatus",
    title: "Billing Status",
    id: "billStatus",
    name: "billStatus",
    required: false,
    options: [
      { value: "TBB", label: "TBB" },
      { value: "ALL BILLED", label: "ALL BILLED" },
      { value: "PART BILLED", label: "PART BILLED" },
      { value: "N/A", label: "N/A" },
    ],
  },
  {
    htmlFor: "supplyStatus",
    title: "Supply Status",
    id: "supplyStatus",
    name: "supplyStatus",
    required: false,
    options: [
      { value: "DISPACHED", label: "DISPACHED" },
      { value: "PENDING", label: "PENDING" },
    ],
  },
  {
    htmlFor: "soType",
    title: "SO Type",
    type: "select",
    id: "soType",
    name: "soType",
    required: false,
    options: [
      { value: "PROJECT", label: "PROJECT" },
      { value: "SERVICE", label: "SERVICE" },
      { value: "AMC", label: "AMC" },
    ],
  },
  {
    htmlFor: "entityType",
    title: "Entity",
    type: "select",
    id: "entityType",
    name: "entityType",
    required: false,
    options: [
      { value: "SI DELHI", label: "SI-DELHI" },
      { value: "SI PUNE", label: "SI-PUNE" },
      { value: "SI NOIDA", label: "SI-NOIDA" },
      { value: "MS DELHI", label: "MS-DELHI" },
    ],
  },
  {
    htmlFor: "status",
    title: "Status",
    type: "select",
    id: "status",
    name: "status",
    required: false,
    options: [
      { value: "upcoming", label: "Up Coming" },
      { value: "pending", label: "pending" },
      { value: "completed", label: "completed" },
      { value: "running", label: "running" },
      { value: "cancelled", label: "cancelled" },
    ],
  },
  {
    htmlFor: "StartChecklist",
    title: "Start Check List Status",
    type: "select",
    id: "StartChecklist",
    name: "StartChecklist",
    required: false,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
  },
  {
    htmlFor: "priority",
    title: "Priority",
    type: "select",
    id: "priority",
    name: "priority",
    required: false,
    options: [
      { value: "high", label: "High" },
      { value: "medium", label: "Medium" },
      { value: "low", label: "Low" },
    ],
  },
  {
    htmlFor: "service",
    title: "Service",
    type: "select",
    id: "service",
    name: "service",
    required: false,
    options: [
      { value: "Service Included", label: "Include" },
      { value: "Service not included", label: "Not Included" },
    ],
  },
  {
    title: "Description",
    id: "description",
    name: "description",
    htmlFor: "description",
    maxLength: 400,
    rows: 4,
    placeholder: "Enter the project Description",
    required: false,
  },
  {
    htmlFor: "EndChecklist",
    title: "End Check List Status",
    type: "select",
    id: "EndChecklist",
    name: "EndChecklist",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "ContactPersonName",
    title: "Contact Person Name",
    type: "text",
    id: "ContactPersonName",
    name: "ContactPersonName",
    placeholder: "Enter the contact person name",
    required: true,
  },
  {
    htmlFor: "ContactPersonNumber",
    title: "Contact Person Number",
    type: "text",
    id: "ContactPersonNumber",
    name: "ContactPersonNumber",
    placeholder: "Enter the contact person number",
    required: true,
  },
  {
    htmlFor: "BackupSubmission",
    title: "Backup Submission Status",
    type: "select",
    id: "BackupSubmission",
    name: "BackupSubmission",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "ExpensSubmission",
    title: "Expense Submission Status",
    type: "select",
    id: "ExpensSubmission",
    name: "ExpensSubmission",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
];

export const UserSideConst = [
  {
    htmlFor: "projectName",
    title: "Project Name",
    type: "text",
    id: "projectName",
    name: "projectName",
    placeholder: "Enter the project name",
    required: true,
    readOnly: true,
  },
  {
    htmlFor: "duration",
    title: "Project Duration",
    type: "text",
    id: "duration",
    name: "duration",
    placeholder: "Enter the project duration",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "expenseScope",
    title: "Expenses Scope",
    type: "text",
    id: "expenseScope",
    name: "expenseScope",
    placeholder: "Enter the Expense Scope",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "workScope",
    title: "Work Scope",
    type: "text",
    id: "workScope",
    name: "workScope",
    placeholder: "Enter the work scope",
    required: true,
    maxLength: 500,
    rows: 3,
  },
  {
    htmlFor: "jobNumber",
    title: "Project Job Number",
    type: "text",
    id: "jobNumber",
    name: "jobNumber",
    placeholder: "Enter the project job number",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "orderNumber",
    title: "Order Number",
    type: "text",
    id: "orderNumber",
    name: "orderNumber",
    placeholder: "Enter the Order number",
    required: false,
    readOnly: true,
  },
  {
    htmlFor: "momsrNo",
    title: "MOM Sr. No.",
    type: "text",
    id: "momsrNo",
    name: "momsrNo",
    placeholder: "Enter the MOM number",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "startDate",
    title: "Project Start Date",
    type: "date",
    id: "startDate",
    name: "startDate",
    placeholder: "Select the project start date",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "endDate",
    title: "Project End Date",
    type: "date",
    id: "endDate",
    name: "endDate",
    placeholder: "Select the project end date",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "visitDate",
    title: "Site Visit Start Date",
    type: "date",
    id: "visitDate",
    name: "visitDate",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "visitendDate",
    title: "Site Visit End Date",
    type: "date",
    id: "visitendDate",
    name: "visitendDate",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "momDate",
    title: "Mom Date",
    type: "date",
    id: "momDate",
    name: "momDate",
    required: false,
    readOnly: false,
  },
  {
    htmlFor: "location",
    title: "Location",
    type: "text",
    id: "location",
    name: "location",
    placeholder: "Enter the project location",
    required: true,
    readOnly: true,
  },
  {
    htmlFor: "engineerName",
    title: "Assigned Engineer Name",
    type: "text",
    id: "engineerName",
    name: "engineerName",
    placeholder: "Enter the Engineer Name",
    required: true,
    readOnly: true,
  },
  {
    htmlFor: "finalMomnumber",
    title: "Final Mom",
    type: "text",
    id: "finalMomnumber",
    name: "finalMomnumber",
    placeholder: "Enter the final mom number",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "billStatus",
    title: "Billing Status",
    id: "billStatus",
    name: "billStatus",
    required: true,
    options: [
      { value: "TBB", label: "TBB" },
      { value: "ALL BILLED", label: "ALL BILLED" },
      { value: "PART BILLED", label: "PART BILLED" },
      { value: "N/A", label: "N/A" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "supplyStatus",
    title: "Supply Status",
    id: "supplyStatus",
    name: "supplyStatus",
    required: true,
    options: [
      { value: "DISPACHED", label: "DISPACHED" },
      { value: "PENDING", label: "PENDING" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "soType",
    title: "SO Type",
    type: "select",
    id: "soType",
    name: "soType",
    required: false,
    options: [
      { value: "PROJECT", label: "PROJECT" },
      { value: "SERVICE", label: "SERVICE" },
      { value: "AMC", label: "AMC" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "entityType",
    title: "Entity",
    type: "select",
    id: "entityType",
    name: "entityType",
    required: false,
    options: [
      { value: "SI DELHI", label: "SI-DELHI" },
      { value: "SI PUNE", label: "SI-PUNE" },
      { value: "SI NOIDA", label: "SI-NOIDA" },
      { value: "MS DELHI", label: "MS-DELHI" },
    ],
    readOnly: true,
  },
  {
    htmlFor: "StartChecklist",
    title: "Start Check List Status",
    type: "select",
    id: "StartChecklist",
    name: "StartChecklist",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "currentEngineerName",
    title: "Enter your name",
    type: "text",
    id: "currentEngineerName",
    name: "currentEngineerName",
    placeholder: "Enter your name",
    required: true,
    readOnly: false,
  },
  {
    htmlFor: "EndChecklist",
    title: "End Check List Status",
    type: "select",
    id: "EndChecklist",
    name: "EndChecklist",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "BackupSubmission",
    title: "Backup Submission Status",
    type: "select",
    id: "BackupSubmission",
    name: "BackupSubmission",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
  {
    htmlFor: "ExpensSubmission",
    title: "Expense Submission Status",
    type: "select",
    id: "ExpensSubmission",
    name: "ExpensSubmission",
    required: true,
    options: [
      { value: "N/A", label: "N/A" },
      { value: "YES", label: "YES" },
      { value: "NO", label: "NO" },
    ],
    readOnly: false,
  },
];
